move_group:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner

    request_adapters:
      - default_planner_request_adapters/AddTimeParameterization
      - default_planner_request_adapters/FixWorkspaceBounds
      - default_planner_request_adapters/FixStartStateBounds
      - default_planner_request_adapters/FixStartStateCollision
      - default_planner_request_adapters/FixStartStatePathConstraints

    planner_configs:
      RRTConnect:
        type: geometric::RRTConnect
        range: 0.1

    start_state_max_bounds_error: 0.1

