
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
      state_publish_rate: 50.0
      action_monitor_rate: 10.0

    gripper_controller:
      type: position_controllers/GripperActionController
      joint: joint_4
      use_speed_interface: true
      state_publish_rate: 50.0
      action_monitor_rate: 10.0
