controller_manager:
  ros__parameters:
    update_rate: 100  # Match update rate with ros2_controllers.yaml

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

    state_publish_rate: 50.0
    action_monitor_rate: 10.0

    initial_positions:
      joint_1: 0.0
      joint_2: 0.0
      joint_3: 0.0

gripper_controller:
  ros__parameters:
    joint: joint_4

    state_publish_rate: 50.0
    action_monitor_rate: 10.0

    initial_positions:
      joint_4: 0.0
